#!/usr/bin/python3

import sys
import os

tests_file = open( "tests.json", "w" )
tests_file.writelines( "{\r\n" )
tests_file.writelines( "\t\"Available commutations\" : {\"0V-P_1\" : [\"Emitter\"], \"0V-P_2\" : [\"Emitter\"], \"0V-P_3\" : [\"Emitter\"], \"+Uz_1\" : [\"Emitter\"], \"+Uz_2\" : [\"Emitter\"], \"+Uz_3\" : [\"Emitter\"], \"Uds_1\" : [\"Emitter\", \"Collector\", \"R1_21K\", \"R2_900R\", \"R3_9.1K\"], \"Uds_2\" : [\"Emitter\", \"Collector\", \"R1_21K\", \"R2_900R\", \"R3_9.1K\"], \"0V-GND\" : [\"Emitter\", \"Collector\", \"0V\", \"0V - Emitter\"], \"Uc\" : [], \"D0-L\" : [], \"Vcc\" : [\"Emitter\", \"Collector\", \"0V\", \"0V - Emitter\", \"3.3V\"], \"A0\" : [\"Emitter\", \"0V\", \"0.4V_LOW\", \"2.4V_HIGH\", \"3.3V\", \"0V - Emitter\"], \"A1\" : [\"Emitter\", \"0V\", \"0.4V_LOW\", \"2.4V_HIGH\", \"3.3V\", \"0V - Emitter\"], \"A2\" : [\"Emitter\", \"0V\", \"0.4V_LOW\", \"2.4V_HIGH\", \"3.3V\", \"0V - Emitter\"], \"E0-L\" : [\"Emitter\", \"0V\", \"0.4V_LOW\", \"2.4V_HIGH\", \"3.3V\", \"0V - Emitter\"], \"A3\" : [\"Emitter\", \"0V\", \"0.4V_LOW\", \"2.4V_HIGH\", \"3.3V\", \"0V - Emitter\"], \"DSI1\" : [\"Emitter\", \"Collector\"], \"DSI2\" : [\"Emitter\", \"Collector\"], \"DSI3\" : [\"Emitter\", \"Collector\"], \"DSI4\" : [\"Emitter\", \"Collector\"], \"DSI5\" : [\"Emitter\", \"Collector\"], \"DSI6\" : [\"Emitter\", \"Collector\"], \"DSI7\" : [\"Emitter\", \"Collector\"], \"DSI8\" : [\"Emitter\", \"Collector\"], \"DSI9\" : [\"Emitter\", \"Collector\"], \"DSI10\" : [\"Emitter\", \"Collector\"], \"DSI11\" : [\"Emitter\", \"Collector\"], \"DSI12\" : [\"Emitter\", \"Collector\"], \"DSI13\" : [\"Emitter\", \"Collector\"], \"DSI14\" : [\"Emitter\", \"Collector\"], \"DSI15\" : [\"Emitter\", \"Collector\"], \"DSI16\" : [\"Emitter\", \"Collector\"], \"NC\" : []},\r\n" )
tests_file.writelines( "\t\"Relay assigments\" : {\"Relay#1\" : \"A2 - 3.3V\", \"Relay#2\" : \"A1 - Emitter\", \"Relay#3\" : \"A0 - 0.4V_LOW\", \"Relay#4\" : \"0V-GND - Emitter\", \"Relay#5\" : \"Uds_1 - Emitter\", \"Relay#6\" : \"+Uz_2 - Emitter\", \"Relay#7\" : \"A1 - 0V\", \"Relay#8\" : \"A1 - 0.4V_LOW\", \"Relay#9\" : \"A1 - 2.4V_HIGH\", \"Relay#10\" : \"A1 - 3.3V\", \"Relay#11\" : \"0V-P_1 - Emitter\", \"Relay#12\" : \"A0 - 0V\", \"Relay#13\" : \"A0 - 3.3V\", \"Relay#14\" : \"0V-GND - 0V\", \"Relay#15\" : \"0V-GND - Collector\", \"Relay#16\" : \"Uds_1 - R1_21K\", \"Relay#17\" : \"0V-P_2 - Emitter\", \"Relay#18\" : \"A0 - Emitter\", \"Relay#19\" : \"A0 - 2.4V_HIGH\", \"Relay#20\" : \"Uds_1 - R2_900R\", \"Relay#21\" : \"Uds_1 - Collector\", \"Relay#22\" : \"Uds_1 - R3_9.1K\", \"Relay#23\" : \"0V-P_3 - Emitter\", \"Relay#24\" : \"A2 - 2.4V_HIGH\", \"Relay#25\" : \"A2 - 0.4V_LOW\", \"Relay#26\" : \"A2 - 0V\", \"Relay#27\" : \"A3 - 0V\", \"Relay#28\" : \"A3 - 0.4V_LOW\", \"Relay#29\" : \"+Uz_1 - Emitter\", \"Relay#30\" : \"Uds_2 - R3_9.1K\", \"Relay#31\" : \"Uds_2 - R2_900R\", \"Relay#32\" : \"E0-L - 2.4V_HIGH\", \"Relay#33\" : \"A2 - Emitter\", \"Relay#34\" : \"A3 - Emitter\", \"Relay#35\" : \"E0-L - 0V\", \"Relay#36\" : \"+Uz_3 - Emitter\", \"Relay#37\" : \"Uds_2 - Emitter\", \"Relay#38\" : \"Uds_2 - R1_21K\", \"Relay#39\" : \"DSI14 - Collector\", \"Relay#40\" : \"DSI14 - Emitter\", \"Relay#41\" : \"DSI13 - Emitter\", \"Relay#42\" : \"DSI12 - Emitter\", \"Relay#43\" : \"DSI13 - Collector\", \"Relay#44\" : \"DSI9 - Collector\", \"Relay#45\" : \"DSI16 - Emitter\", \"Relay#46\" : \"DSI9 - Emitter\", \"Relay#47\" : \"DSI1 - Collector\", \"Relay#48\" : \"DSI12 - Collector\", \"Relay#49\" : \"DSI6 - Emitter\", \"Relay#50\" : \"DSI6 - Collector\", \"Relay#51\" : \"DSI1 - Emitter\", \"Relay#52\" : \"DSI16 - Collector\", \"Relay#53\" : \"DSI11 - Collector\", \"Relay#54\" : \"DSI11 - Emitter\", \"Relay#55\" : \"DSI5 - Collector\", \"Relay#56\" : \"DSI5 - Emitter\", \"Relay#57\" : \"DSI2 - Emitter\", \"Relay#58\" : \"DSI3 - Emitter\", \"Relay#59\" : \"DSI4 - Collector\", \"Relay#60\" : \"DSI15 - Emitter\", \"Relay#61\" : \"DSI2 - Collector\", \"Relay#62\" : \"DSI3 - Collector\", \"Relay#63\" : \"DSI4 - Emitter\", \"Relay#64\" : \"DSI8 - Collector\", \"Relay#65\" : \"DSI10 - Collector\", \"Relay#66\" : \"DSI10 - Emitter\", \"Relay#67\" : \"E0-L - 3.3V\", \"Relay#68\" : \"DSI15 - Collector\", \"Relay#69\" : \"DSI7 - Emitter\", \"Relay#70\" : \"DSI7 - Collector\", \"Relay#71\" : \"DSI8 - Emitter\", \"Relay#72\" : \"Vcc - Emitter\", \"Relay#73\" : \"Vcc - 3.3V\", \"Relay#74\" : \"Vcc - 0V\", \"Relay#75\" : \"E0-L - 0.4V_LOW\", \"Relay#76\" : \"A3 - 3.3V\", \"Relay#77\" : \"A3 - 2.4V_HIGH\", \"Relay#78\" : \"Uds_2 - Collector\", \"Relay#79\" : \"Vcc - Collector\", \"Relay#80\" : \"E0-L - Emitter\"},\r\n" )

for i in range( 1, 201 ):

    if( i < 200 ) : tests_file.writelines( "\t\"Test#{0}\" : {{\r\n\t\t\"0V-P_1\" : \"N/C\",\r\n\t\t\"0V-P_2\" : \"N/C\",\r\n\t\t\"0V-P_3\" : \"N/C\",\r\n\t\t\"+Uz_1\" : \"N/C\",\r\n\t\t\"+Uz_2\" : \"N/C\",\r\n\t\t\"+Uz_3\" : \"N/C\",\r\n\t\t\"Uds_1\" : \"N/C\",\r\n\t\t\"Uds_2\" : \"N/C\",\r\n\t\t\"0V-GND\" : \"N/C\",\r\n\t\t\"Uc\" : \"N/C\",\r\n\t\t\"D0-L\" : \"N/C\",\r\n\t\t\"Vcc\" : \"N/C\",\r\n\t\t\"A0\" : \"N/C\",\r\n\t\t\"A1\" : \"N/C\",\r\n\t\t\"A2\" : \"N/C\",\r\n\t\t\"E0-L\" : \"N/C\",\r\n\t\t\"A3\" : \"N/C\",\r\n\t\t\"DSI1\" : \"N/C\",\r\n\t\t\"DSI2\" : \"N/C\",\r\n\t\t\"DSI3\" : \"N/C\",\r\n\t\t\"DSI4\" : \"N/C\",\r\n\t\t\"DSI5\" : \"N/C\",\r\n\t\t\"DSI6\" : \"N/C\",\r\n\t\t\"DSI7\" : \"N/C\",\r\n\t\t\"DSI8\" : \"N/C\",\r\n\t\t\"DSI9\" : \"N/C\",\r\n\t\t\"DSI10\" : \"N/C\",\r\n\t\t\"DSI11\" : \"N/C\",\r\n\t\t\"DSI12\" : \"N/C\",\r\n\t\t\"DSI13\" : \"N/C\",\r\n\t\t\"DSI14\" : \"N/C\",\r\n\t\t\"DSI15\" : \"N/C\",\r\n\t\t\"DSI16\" : \"N/C\",\r\n\t\t\"NC\" : \"N/C\"\r\n\t}},\r\n\r\n".format( i ))
    else : tests_file.writelines( "\t\"Test#{0}\" : {{\r\n\t\t\"0V-P_1\" : \"N/C\",\r\n\t\t\"0V-P_2\" : \"N/C\",\r\n\t\t\"0V-P_3\" : \"N/C\",\r\n\t\t\"+Uz_1\" : \"N/C\",\r\n\t\t\"+Uz_2\" : \"N/C\",\r\n\t\t\"+Uz_3\" : \"N/C\",\r\n\t\t\"Uds_1\" : \"N/C\",\r\n\t\t\"Uds_2\" : \"N/C\",\r\n\t\t\"0V-GND\" : \"N/C\",\r\n\t\t\"Uc\" : \"N/C\",\r\n\t\t\"D0-L\" : \"N/C\",\r\n\t\t\"Vcc\" : \"N/C\",\r\n\t\t\"A0\" : \"N/C\",\r\n\t\t\"A1\" : \"N/C\",\r\n\t\t\"A2\" : \"N/C\",\r\n\t\t\"E0-L\" : \"N/C\",\r\n\t\t\"A3\" : \"N/C\",\r\n\t\t\"DSI1\" : \"N/C\",\r\n\t\t\"DSI2\" : \"N/C\",\r\n\t\t\"DSI3\" : \"N/C\",\r\n\t\t\"DSI4\" : \"N/C\",\r\n\t\t\"DSI5\" : \"N/C\",\r\n\t\t\"DSI6\" : \"N/C\",\r\n\t\t\"DSI7\" : \"N/C\",\r\n\t\t\"DSI8\" : \"N/C\",\r\n\t\t\"DSI9\" : \"N/C\",\r\n\t\t\"DSI10\" : \"N/C\",\r\n\t\t\"DSI11\" : \"N/C\",\r\n\t\t\"DSI12\" : \"N/C\",\r\n\t\t\"DSI13\" : \"N/C\",\r\n\t\t\"DSI14\" : \"N/C\",\r\n\t\t\"DSI15\" : \"N/C\",\r\n\t\t\"DSI16\" : \"N/C\",\r\n\t\t\"NC\" : \"N/C\"\r\n\t}}\r\n".format( i ))
    
tests_file.writelines( "}" )
tests_file.close()
sys.exit( 0 );
